In [6]:
# import essential libraries 
import pandas as pd
from sqlalchemy import create_engine

# create engine
engine = create_engine("mysql+mysqlconnector://root:root@localhost/enterpriceBankingAnalyticsDB")

#### 1. Branch-wise transaction contribution %

In [ ]:
q1="""
    SELECT 
        BranchID,
        BranchName,
        transaction_amount,
        ROUND(
            transaction_amount * 100 / (
                SELECT SUM(Amount) FROM transactions
            ),
            2
        ) AS contribution
    FROM
    (
        SELECT
            b.BranchID,
            b.BranchName,
            SUM(t.Amount) AS transaction_amount
        FROM branches b
        JOIN transactions t
            ON b.BranchID=t.BranchID
        GROUP BY b.BranchID,
            b.BranchName
    ) AS t
    ORDER BY contribution DESC
"""

df1=pd.read_sql(q1, engine)
df1

    BranchID BranchName  transaction_amount  contribution
0         47  Branch 47          2377253.37          2.15
1          9   Branch 9          2357390.82          2.13
2         27  Branch 27          2343831.35          2.12
3         44  Branch 44          2330248.66          2.11
4         25  Branch 25          2331686.83          2.11
5         49  Branch 49          2332193.00          2.11
6         46  Branch 46          2318917.16          2.10
7         50  Branch 50          2315380.53          2.09
8         39  Branch 39          2312205.10          2.09
9         15  Branch 15          2315869.40          2.09
10        24  Branch 24          2301427.34          2.08
11         8   Branch 8          2300901.12          2.08
12         6   Branch 6          2285035.84          2.07
13        34  Branch 34          2290812.26          2.07
14        21  Branch 21          2283558.83          2.06
15         4   Branch 4          2268319.65          2.05
16        14  Branch 14          2255136.57          2.04
17        48  Branch 48          2256018.52          2.04
18        36  Branch 36          2251426.42          2.03
19        45  Branch 45          2243215.51          2.03
20        18  Branch 18          2222853.94          2.01
21        22  Branch 22          2221480.08          2.01
22        17  Branch 17          2218937.61          2.01
23        16  Branch 16          2210367.70          2.00
24        41  Branch 41          2211436.55          2.00
25        38  Branch 38          2213801.29          2.00
26        28  Branch 28          2218276.75          2.00
27        29  Branch 29          2202238.33          1.99
28         2   Branch 2          2201589.86          1.99
29        42  Branch 42          2189266.71          1.98
30        30  Branch 30          2191143.01          1.98
31        32  Branch 32          2175684.21          1.97
32         3   Branch 3          2177639.84          1.97
33         7   Branch 7          2180412.52          1.97
34        35  Branch 35          2171823.68          1.96
35        10  Branch 10          2158748.18          1.95
36         1   Branch 1          2153155.78          1.95
37        43  Branch 43          2150295.76          1.94
38        40  Branch 40          2137560.94          1.93
39        12  Branch 12          2136192.97          1.93
40         5   Branch 5          2110588.26          1.91
41        37  Branch 37          2112454.44          1.91
42        26  Branch 26          2097559.39          1.90
43        20  Branch 20          2101210.58          1.90
44        31  Branch 31          2093929.38          1.89
45        23  Branch 23          2075379.49          1.88
46        13  Branch 13          2062877.41          1.86
47        19  Branch 19          2062793.86          1.86
48        11  Branch 11          2055815.35          1.86
49        33  Branch 33          2058513.04          1.86

#### 2. Customers with loan but no recent transaction

In [10]:
q2="""
    SELECT
        c.FirstName,
        c.LastName,
        l.PrincipalAmount,
        t.TransactionID,
        t.TransactionDate
    FROM customers c 
    LEFT JOIN accounts a 
        ON c.CustomerID=a.CustomerID
    LEFT JOIN loans l 
        ON a.AccountID=l.AccountID
    LEFT JOIN transactions t 
        ON a.AccountID=t.AccountOriginID AND t.TransactionDate>=DATE_SUB(CURDATE(), INTERVAL 6 MONTH)
    WHERE t.TransactionID IS NULL AND l.PrincipalAmount IS NOT NULL
"""

df2=pd.read_sql(q2, engine)
df2.head(20)

   FirstName   LastName  PrincipalAmount TransactionID TransactionDate
0       Rush       Rush         63899.00          None            None
1       Troy   Hatfield         22288.38          None            None
2         My    Herring         15797.11          None            None
3     Justin      Hicks         37284.69          None            None
4       Dion     Nelson         65948.85          None            None
5    Barrett       Wise         28952.23          None            None
6     Felipe      Munoz         64001.15          None            None
7     Sherly     Spears         47534.75          None            None
8       Rush       Rush         82121.58          None            None
9       Deon      Kline         51864.56          None            None
10     Tyler       Burt         27964.95          None            None
11   Lindsay  Contreras         34767.61          None            None
12     Somer     Gibson         20092.86          None            None
13     Magen     Hansen         62585.34          None            None
14     Lenna    Workman         35503.34          None            None
15   Gertrud      Brown         89097.17          None            None
16    Mellie     Walker         60253.22          None            None
17    Jarred  Valentine         81509.04          None            None
18      Minh      Horne         10436.77          None            None
19  Clifford      Moore         36366.26          None            None

#### 3. Top 10% customers ka balance contribution

In [14]:
q3="""
    WITH customer_amounts AS (
        SELECT
            c.CustomerID,
            c.FirstName,
            c.LastName,
            SUM(a.Balance) AS total_balance
        FROM customers c 
        JOIN accounts a 
            ON c.CustomerID=a.CustomerID
        GROUP BY c.CustomerID,
            c.FirstName,
            c.LastName
    ),
    divide_buckets AS (
        SELECT
            CustomerID,
            FirstName,
            LastName,
            total_balance,
            NTILE(10) OVER(ORDER BY total_balance DESC) AS customer_buckets
        FROM customer_amounts
    )
    
    SELECT
        ROUND(
            SUM(total_balance) * 100 / (
                SELECT SUM(Balance) FROM accounts
            ),
            2
        ) AS contribution
    FROM divide_buckets
    WHERE customer_buckets = 1;
"""

df3=pd.read_sql(q3, engine)
print("Top 10% customers balance contribution: \n",df3)

Top 10% customers balance contribution:
    contribution
0          26.0

#### 4. Running monthly transaction total

In [17]:
q4="""
    SELECT  
        transaction_year,
        transaction_month_name,
        transaction_month_no,
        SUM(transaction_amount) OVER(ORDER BY transaction_year, transaction_month_no) AS cumulative_transaction_amount
    FROM
    (
        SELECT
            YEAR(TransactionDate) AS transaction_year,
            MONTH(TransactionDate) AS transaction_month_no,
            MONTHNAME(TransactionDate) AS transaction_month_name,
            SUM(Amount) AS transaction_amount
        FROM transactions 
        GROUP BY YEAR(TransactionDate),
            MONTH(TransactionDate)
    ) AS t
"""

df4=pd.read_sql(q4, engine)
df4.head(20)

,transaction_year,transaction_month_name,transaction_month_no,cumulative_transaction_amount
0,2020,January,1,2221593.23
1,2020,February,2,4461156.71
2,2020,March,3,6701341.32
3,2020,April,4,9015007.23
4,2020,May,5,11413191.58
5,2020,June,6,13787895.18
6,2020,July,7,15949922.08
7,2020,August,8,18182716.85
8,2020,September,9,20400325.68
9,2020,October,10,22490004.24
10,2020,November,11,24747299.13
11,2020,December,12,27011366.77
12,2021,January,1,29270168.68
13,2021,February,2,31249408.08
14,2021,March,3,33485582.64
15,2021,April,4,35581782.19
16,2021,May,5,37784951.93
17,2021,June,6,40051351.65
18,2021,July,7,42366857.78
19,2021,August,8,44648678.64

#### 5. Composite branch performance

In [18]:
q5="""
    WITH transaction_volume AS (
        SELECT  
            b.BranchID,
            b.BranchName,
            SUM(t.Amount) AS transaction_amount
        FROM branches b 
        JOIN transactions t 
            ON b.BranchID=t.BranchID
        GROUP BY b.BranchID,
            b.BranchName
    ),
    loan_portfolio AS (
        SELECT
            b.BranchID,
            b.BranchName,
            SUM(l.PrincipalAmount) AS loan_amount
        FROM branches b 
        JOIN transactions t
            ON b.BranchID=t.BranchID
        JOIN accounts a  
            ON t.AccountOriginID=a.AccountID
        JOIN loans l 
            ON a.AccountID=l.AccountID
        GROUP BY b.BranchID,
            b.BranchName
    ),
    customer_count AS (
        SELECT
            b.BranchID,
            b.BranchName,
            COUNT(DISTINCT c.CustomerID) AS total_customers
        FROM branches b 
        JOIN transactions t
            ON b.BranchID=t.BranchID
        JOIN accounts a  
            ON t.AccountOriginID=a.AccountID
        JOIN customers c 
            ON a.CustomerID=c.CustomerID
        GROUP BY b.BranchID,
            b.BranchName
    )
    
    SELECT
        tv.BranchID,
        tv.BranchName,
        tv.transaction_amount,
        lp.loan_amount,
        cc.total_customers
    FROM transaction_volume tv 
    JOIN loan_portfolio lp 
        ON tv.BranchID=lp.BranchID
    JOIN customer_count cc 
        ON lp.BranchID=cc.BranchID
"""

df5=pd.read_sql(q5, engine)
df5

    BranchID BranchName  transaction_amount  loan_amount  total_customers
0         23  Branch 23          2075379.49   8732620.39              495
1         47  Branch 47          2377253.37   8263034.18              527
2          1   Branch 1          2153155.78   8259673.30              505
3         19  Branch 19          2062793.86   8510856.38              492
4         40  Branch 40          2137560.94   9538294.88              484
5         44  Branch 44          2330248.66  10102799.48              523
6         38  Branch 38          2213801.29   8774288.98              503
7          8   Branch 8          2300901.12   8744720.01              502
8         41  Branch 41          2211436.55   9175183.19              496
9         34  Branch 34          2290812.26   8425621.41              507
10        32  Branch 32          2175684.21   8177485.60              504
11        27  Branch 27          2343831.35   9408947.39              533
12        15  Branch 15          2315869.40   8994190.44              520
13        46  Branch 46          2318917.16   9610882.48              513
14        18  Branch 18          2222853.94   9229183.47              528
15        45  Branch 45          2243215.51   9730405.06              486
16        14  Branch 14          2255136.57   8728729.03              507
17        43  Branch 43          2150295.76   9103782.58              487
18        42  Branch 42          2189266.71   8970584.51              489
19         5   Branch 5          2110588.26   7306490.22              493
20        36  Branch 36          2251426.42   8739231.44              509
21        33  Branch 33          2058513.04   7470390.30              485
22        30  Branch 30          2191143.01  10486900.06              491
23        10  Branch 10          2158748.18  10030119.16              502
24         9   Branch 9          2357390.82   9053383.01              524
25        12  Branch 12          2136192.97   9091500.21              485
26        20  Branch 20          2101210.58   7808382.69              496
27        49  Branch 49          2332193.00  11184137.69              517
28        26  Branch 26          2097559.39   8983175.54              499
29        31  Branch 31          2093929.38   7958336.13              499
30        50  Branch 50          2315380.53   9073698.21              513
31        39  Branch 39          2312205.10   9575165.62              497
32        21  Branch 21          2283558.83   9053810.71              499
33        28  Branch 28          2218276.75   9710060.93              486
34        37  Branch 37          2112454.44   8180629.45              502
35        35  Branch 35          2171823.68  10010997.52              505
36         6   Branch 6          2285035.84   8762813.66              494
37        11  Branch 11          2055815.35   8694102.03              474
38        17  Branch 17          2218937.61   8408510.75              508
39        16  Branch 16          2210367.70   8529644.97              518
40        24  Branch 24          2301427.34   9043447.68              500
41         2   Branch 2          2201589.86   6637010.99              490
42        48  Branch 48          2256018.52   8902508.99              504
43         7   Branch 7          2180412.52   8585619.65              492
44        22  Branch 22          2221480.08   9446730.18              500
45        13  Branch 13          2062877.41   7094077.33              484
46         3   Branch 3          2177639.84   9039557.14              472
47         4   Branch 4          2268319.65   8542587.50              495
48        29  Branch 29          2202238.33   9246716.32              520
49        25  Branch 25          2331686.83  10114178.53              516

#### 6. Customer type vs avg balance/loan

In [21]:
q6="""
    SELECT
        c.CustomerID,
        c.FirstName,
        c.LastName,
        AVG(a.Balance) AS avg_balance
    FROM customers c
    JOIN accounts a
        ON c.CustomerID=a.CustomerID
    GROUP BY c.CustomerID,
        c.FirstName,
        c.LastName
"""

df6=pd.read_sql(q6, engine)
df6.head(20)

    CustomerID  FirstName    LastName   avg_balance
0        10330       Joya      Dotson  24851.020000
1        10106     Jenine      Conner  54392.670000
2        10839      Herta    Roberson  84008.770000
3        10765     Junior        Witt  58739.640000
4        10584     Kimiko    Griffith  74097.047500
5        11007        Bob     Shepard  28583.810000
6        10423     Grover      Hansen  23094.253333
7        10219     Glayds      Garcia  77099.605000
8        10096      Paris       Gomez  30134.400000
9        10818     Nikole       Garza  40898.867500
10       10056     Murray     Salazar  44779.270000
11       10899    Corliss      Willis  74750.700000
12       10253    Charita      Farmer   1643.135000
13       10704  Katheleen      Cooley  53810.055000
14       10441    Brendan     Bridges  30158.010000
15       11043    Melodee     Marquez  12950.650000
16       10274    Tonette  Montgomery  67472.510000
17       10565    Gertrud       Brown  44346.345000
18       10628     Fredda    Morrison  46343.170000
19       10987     Rosana       Drake  46697.840000